WINDOW_WIDTH = 800
WINDOW_HEIGHT = 600


H_DIS = (WINDOW_WIDTH / 2) - 25
STARTING_POSITIONS_LEFT = [(-H_DIS,0), (-H_DIS, 20), (-H_DIS,40)]
STARTING_POSITIONS_RIGHT = [(H_DIS,0), (H_DIS, 20), (H_DIS,40)]