WINDOW_WIDTH = 800
WINDOW_HEIGHT = 600
BALL_SPEED_FACTOR = 0.0125

H_DIS = (WINDOW_WIDTH / 2) - 25
STARTING_POSITION_LEFT = (-H_DIS, 0)
STARTING_POSITION_RIGHT = (H_DIS, 0)
PADDLE_MOVING_DISTANCE = 20